# Generated by Django 5.2.17 on 2026-10-04 19:51

import apps.accounts.managers
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('telefono', models.CharField(error_messages={'unique': 'Ya existe una cuenta con este teléfono.'}, help_text='Identificador de acceso: 8 dígitos, sin prefijo ni separadores.', max_length=8, unique=True, validators=[django.core.validators.RegexValidator('\\A[0-9]{8}\\Z', 'Ingresa un teléfono de Nicaragua de 8 dígitos.')], verbose_name='teléfono')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('rol', models.CharField(choices=[('comprador', 'Comprador'), ('artesano', 'Artesano'), ('administrador', 'Administrador')], max_length=20, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, help_text='Una cuenta inactiva no inicia sesión y sus sesiones dejan de ser válidas.', verbose_name='activa')),
                ('is_staff', models.BooleanField(default=False, help_text='Privilegio interno de Django. Solo para cuentas con rol administrador.', verbose_name='acceso a Django Admin')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creada en')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'constraints': [models.CheckConstraint(condition=models.Q(('telefono__regex', '\\A[0-9]{8}\\Z')), name='usuario_telefono_normalizado', violation_error_message='Ingresa un teléfono de Nicaragua de 8 dígitos.'), models.CheckConstraint(condition=models.Q(('rol__in', ['comprador', 'artesano', 'administrador'])), name='usuario_rol_valido'), models.CheckConstraint(condition=models.Q(('is_staff', False), ('rol', 'administrador'), _connector='OR'), name='usuario_staff_requiere_rol_administrador', violation_error_message='Solo una cuenta con rol administrador puede acceder a Django Admin.'), models.CheckConstraint(condition=models.Q(('is_superuser', False), ('rol', 'administrador'), _connector='OR'), name='usuario_superusuario_requiere_rol_administrador', violation_error_message='Solo una cuenta con rol administrador puede ser superusuario.')],
            },
            managers=[
                ('objects', apps.accounts.managers.UsuarioManager()),
            ],
        ),
    ]
