/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ArtesanoIdRouteImport } from './routes/artesano.$id'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as PedidosIdRouteImport } from './routes/pedidos.$id'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as SolicitarProductIdRouteImport } from './routes/solicitar.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtesanoIdRoute = ArtesanoIdRouteImport.update({
  id: '/artesano/$id',
  path: '/artesano/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdRoute = PedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarProductIdRoute = SolicitarProductIdRouteImport.update({
  id: '/solicitar/$productId',
  path: '/solicitar/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/artesano/$id': typeof ArtesanoIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/producto/$id': typeof ProductoIdRoute
  '/solicitar/$productId': typeof SolicitarProductIdRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/artesano/$id': typeof ArtesanoIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/producto/$id': typeof ProductoIdRoute
  '/solicitar/$productId': typeof SolicitarProductIdRoute
  '/pedidos': typeof PedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/artesano/$id': typeof ArtesanoIdRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/producto/$id': typeof ProductoIdRoute
  '/solicitar/$productId': typeof SolicitarProductIdRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/artesano/$id'
    | '/pedidos/$id'
    | '/producto/$id'
    | '/solicitar/$productId'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/artesano/$id'
    | '/pedidos/$id'
    | '/producto/$id'
    | '/solicitar/$productId'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/artesano/$id'
    | '/pedidos/$id'
    | '/producto/$id'
    | '/solicitar/$productId'
    | '/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  ArtesanoIdRoute: typeof ArtesanoIdRoute
  PedidosIdRoute: typeof PedidosIdRoute
  ProductoIdRoute: typeof ProductoIdRoute
  SolicitarProductIdRoute: typeof SolicitarProductIdRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artesano/$id': {
      id: '/artesano/$id'
      path: '/artesano/$id'
      fullPath: '/artesano/$id'
      preLoaderRoute: typeof ArtesanoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id': {
      id: '/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PedidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar/$productId': {
      id: '/solicitar/$productId'
      path: '/solicitar/$productId'
      fullPath: '/solicitar/$productId'
      preLoaderRoute: typeof SolicitarProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  ArtesanoIdRoute: ArtesanoIdRoute,
  PedidosIdRoute: PedidosIdRoute,
  ProductoIdRoute: ProductoIdRoute,
  SolicitarProductIdRoute: SolicitarProductIdRoute,
  PedidosIndexRoute: PedidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
